---
- name: Install Apache WebServer
  hosts: localhost
  become: true
  gather_facts: true
  
  tasks:
    - name: Install Apache on Ubuntu Server
      apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache on CentOS  Server
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "Redhat"