---
- name: user creation
  hosts: all
  become: true
  vars:
    users: [ram,ravi,raju]

  tasks:
    - name: create user
      user:
        name: "{{ item }}"
      with_items: "{{ users }}"


 

  tasks:
  - name: create user
    ansible.builtin.user:
      name: "{{ item }}"
    loop:
      - ram
      - ravi
      - raju